### PR TITLE
Let time flow in same direction in pic that explains almost everything

### PR DESCRIPTION
**Pull request by pimsmeets**
Made a small change in the pictures that explain almost everything - seems more intuitive to let the time flow in the same direction

### CODE REVIEW

**Comment by Baasie** [comment]
Discussed this with @pimsmeets (colleague and friend of mine) and this commits resembles the way Alberto communicates the picture. The feedback from Chris Richardson was to put the arrows differently. I think I would like this picture more, but curious what the rest of you thinks :)

**Comment by NTCoding** [comment]
The new tweaks make sense. The only change I would suggest is that a read model "is observed by" an actor rather "read model observes actor".

**Comment by pimsmeets** [comment]
> The new tweaks make sense. The only change I would suggest is that a read model "is observed by" an actor rather "read model observes actor".

Nice one Nick. That makes sense.

**Comment by yellowbrickc** [comment]
I would say, it is time to make this available for everybody out there 🙂

**Pull request merged**
